# Generated by Django 3.2.25 on 2025-10-05 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='saved_jobs',
            fields=[
                ('saved_jobs_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_role', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('job_location', models.CharField(max_length=255)),
                ('job_salary', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='user_registered',
            fields=[
                ('user_registered_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=225)),
                ('phno', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('district', models.CharField(max_length=225)),
                ('country', models.CharField(max_length=225)),
                ('pincode', models.CharField(max_length=225)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal_app.user_login')),
            ],
        ),
    ]
