# Generated by Django 3.2.25 on 2025-10-08 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved_jobs',
            name='job_experience',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saved_jobs',
            name='login',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='job_portal_app.user_login'),
            preserve_default=False,
        ),
    ]
